package com.urbondo.announcement.service.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

@DynamoDBTable(tableName = "urbondo-announcement")
public final class AnnouncementEntity {
    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @DynamoDBAttribute
    private String title;

    @DynamoDBAttribute
    private String body;

    @DynamoDBAttribute
    @DynamoDBIndexHashKey(attributeName = "email", globalSecondaryIndexName = "email")
    private String categoryId;

    public AnnouncementEntity() {
    }

    public AnnouncementEntity(String id, String title, String body, String categoryId) {
        this.id = id;
        this.title = title;
        this.body = body;
        this.categoryId = categoryId;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public String getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId;
    }
}
